<?php

namespace Database\Seeders;

use App\Models\Obat;
use Illuminate\Database\Seeder;

class ObatSeeder extends Seeder
{
    private const HARGA_RANGES = [
        'Tablet' => [500, 15000],
        'Kapsul' => [1000, 25000],
        'Botol' => [5000, 50000],
        'Tube' => [3000, 30000],
        'Ampul' => [2000, 40000],
        'Sachet' => [500, 5000],
    ];

    private const VEN_MAP = [
        '92000634' => 'V',
        '92000756' => 'V',
        '92000435' => 'V',
        '92000715' => 'V',
        '92000564' => 'V',
        '92000347' => 'V',
        '92000986' => 'V',
        '92000146' => 'E',
        '92000637' => 'E',
        '92002856' => 'E',
        '92000124' => 'E',
        '92000281' => 'E',
        '92000407' => 'E',
        '92001058' => 'E',
        '92000406' => 'E',
        '92000486' => 'E',
        '92000234' => 'E',
        '92000881' => 'E',
        '92000472' => 'E',
        '92000770' => 'E',
        '92000914' => 'E',
        '92000209' => 'E',
        '92000163' => 'E',
        '92001267' => 'E',
        '92000185' => 'E',
        '92001081' => 'E',
        '92000535' => 'E',
        '92001960' => 'E',
        '92000139' => 'E',
        '92001205' => 'E',
        '92003720' => 'E',
        '92000860' => 'E',
        '92000366' => 'E',
        '92001386' => 'E',
        '92000255' => 'E',
        '92000572' => 'E',
        '92000706' => 'E',
        '92000445' => 'E',
        '92000344' => 'E',
        '92000798' => 'N',
        '92002094' => 'N',
        '92000653' => 'N',
        '92000517' => 'N',
        '92000129' => 'N',
        '92001124' => 'N',
        '92000809' => 'N',
        '92001885' => 'N',
        '92000201' => 'N',
        '92002848' => 'N',
        '92000403' => 'N',
        '92000731' => 'N',
        '92001095' => 'N',
        '92000465' => 'N',
    ];

    public function run(): void
    {
        $obatList = [
            [
                'kode_obat' => '92000146',
                'nama_obat' => 'Albendazole Tablet 400 mg',
                'nama_generik' => 'Albendazole',
                'kategori' => 'Antelmintik',
                'satuan' => 'Tablet',
                'kekuatan' => '400 mg',
                'bentuk_sediaan' => 'tablet',
                'ven_kategori' => 'E',
            ],
            [
                'kode_obat' => '92000637',
                'nama_obat' => 'Albendazole 200 mg/5 mL Suspensi',
                'nama_generik' => 'Albendazole',
                'kategori' => 'Antelmintik',
                'satuan' => 'Botol',
                'kekuatan' => '200 mg/5 mL',
                'bentuk_sediaan' => 'sirup',
                'ven_kategori' => 'E',
            ],
            [
                'kode_obat' => '92002856',
                'nama_obat' => 'Albendazole 400 mg/5 mL Suspensi',
                'nama_generik' => 'Albendazole',
                'kategori' => 'Antelmintik',
                'satuan' => 'Botol',
                'kekuatan' => '400 mg/5 mL',
                'bentuk_sediaan' => 'sirup',
                'ven_kategori' => 'E',
            ],
            [
                'kode_obat' => '92000124',
                'nama_obat' => 'Alopurinol Tablet 300 mg',
                'nama_generik' => 'Alopurinol',
                'kategori' => 'Antigout',
                'satuan' => 'Tablet',
                'kekuatan' => '300 mg',
                'bentuk_sediaan' => 'tablet',
                'ven_kategori' => 'E',
            ],
            [
                'kode_obat' => '92000281',
                'nama_obat' => 'Alopurinol Tablet 100 mg',
                'nama_generik' => 'Alopurinol',
                'kategori' => 'Antigout',
                'satuan' => 'Tablet',
                'kekuatan' => '100 mg',
                'bentuk_sediaan' => 'tablet',
                'ven_kategori' => 'E',
            ],
            [
                'kode_obat' => '92000407',
                'nama_obat' => 'Amlodipin Tablet 10 mg',
                'nama_generik' => 'Amlodipin',
                'kategori' => 'Kardiovaskular',
                'satuan' => 'Tablet',
                'kekuatan' => '10 mg',
                'bentuk_sediaan' => 'tablet',
                'ven_kategori' => 'E',
            ],
            [
                'kode_obat' => '92001058',
                'nama_obat' => 'Amlodipin Tablet 5 mg',
                'nama_generik' => 'Amlodipin',
                'kategori' => 'Kardiovaskular',
                'satuan' => 'Tablet',
                'kekuatan' => '5 mg',
                'bentuk_sediaan' => 'tablet',
                'ven_kategori' => 'E',
            ],
            [
                'kode_obat' => '92000406',
                'nama_obat' => 'Amoxicillin Sirup Kering 250 mg/5 mL',
                'nama_generik' => 'Amoxicillin',
                'kategori' => 'Antiinfeksi',
                'satuan' => 'Botol',
                'kekuatan' => '250 mg/5 mL',
                'bentuk_sediaan' => 'sirup',
                'ven_kategori' => 'E',
            ],
            [
                'kode_obat' => '92000486',
                'nama_obat' => 'Amoxicillin Sirup Kering 125 mg/5 mL',
                'nama_generik' => 'Amoxicillin',
                'kategori' => 'Antiinfeksi',
                'satuan' => 'Botol',
                'kekuatan' => '125 mg/5 mL',
                'bentuk_sediaan' => 'sirup',
                'ven_kategori' => 'E',
            ],
            [
                'kode_obat' => '92000234',
                'nama_obat' => 'Amoxicillin Sirup Kering 100 mg/5 mL',
                'nama_generik' => 'Amoxicillin',
                'kategori' => 'Antiinfeksi',
                'satuan' => 'Botol',
                'kekuatan' => '100 mg/5 mL',
                'bentuk_sediaan' => 'sirup',
                'ven_kategori' => 'E',
            ],
            [
                'kode_obat' => '92000881',
                'nama_obat' => 'Amoxicillin Tablet 500 mg',
                'nama_generik' => 'Amoxicillin',
                'kategori' => 'Antiinfeksi',
                'satuan' => 'Tablet',
                'kekuatan' => '500 mg',
                'bentuk_sediaan' => 'tablet',
                'ven_kategori' => 'E',
            ],
            [
                'kode_obat' => '92000798',
                'nama_obat' => 'Antasida (Aluminium Hidroksida 200 mg; Magnesium Hidroksida 200 mg) Tablet Kunyah',
                'nama_generik' => 'Aluminium Hidroksida; Magnesium Hidroksida',
                'kategori' => 'Pencernaan',
                'satuan' => 'Tablet',
                'kekuatan' => '200 mg; 200 mg',
                'bentuk_sediaan' => 'tablet',
                'ven_kategori' => 'N',
            ],
            [
                'kode_obat' => '92002094',
                'nama_obat' => 'Antasida (Aluminium Hidroksida 200 mg; Magnesium Hidroksida 200 mg/5 mL) Suspensi',
                'nama_generik' => 'Aluminium Hidroksida; Magnesium Hidroksida',
                'kategori' => 'Pencernaan',
                'satuan' => 'Botol',
                'kekuatan' => '200 mg; 200 mg/5 mL',
                'bentuk_sediaan' => 'sirup',
                'ven_kategori' => 'N',
            ],
            [
                'kode_obat' => '92000653',
                'nama_obat' => 'Ferrous Fumarate 60 mg / Folic Acid 0,4 mg Tablet Salut Gula',
                'nama_generik' => 'Ferrous Fumarate; Folic Acid',
                'kategori' => 'Vitamin & Suplemen',
                'satuan' => 'Tablet',
                'kekuatan' => '60 mg; 0,4 mg',
                'bentuk_sediaan' => 'tablet',
                'ven_kategori' => 'N',
            ],
            [
                'kode_obat' => '91000255',
                'nama_obat' => 'Loratadin Tablet 10 mg',
                'nama_generik' => 'Loratadin',
                'kategori' => 'Antialergi & Imunologi',
                'satuan' => 'Tablet',
                'kekuatan' => '10 mg',
                'bentuk_sediaan' => 'tablet',
                'ven_kategori' => 'E',
            ],
            [
                'kode_obat' => '92000139',
                'nama_obat' => 'Domperidon Maleate Tablet 10 mg',
                'nama_generik' => 'Domperidon Maleate',
                'kategori' => 'Pencernaan',
                'satuan' => 'Tablet',
                'kekuatan' => '10 mg',
                'bentuk_sediaan' => 'tablet',
                'ven_kategori' => 'E',
            ],
            [
                'kode_obat' => '92001205',
                'nama_obat' => 'Domperidon Maleate 5 mg/5 mL Suspensi',
                'nama_generik' => 'Domperidon Maleate',
                'kategori' => 'Pencernaan',
                'satuan' => 'Botol',
                'kekuatan' => '5 mg/5 mL',
                'bentuk_sediaan' => 'sirup',
                'ven_kategori' => 'E',
            ],
            [
                'kode_obat' => '92000403',
                'nama_obat' => 'Mikonazol Krim 2%',
                'nama_generik' => 'Mikonazol',
                'kategori' => 'Kulit & Topikal',
                'satuan' => 'Tube',
                'kekuatan' => '2%',
                'bentuk_sediaan' => 'salep',
                'ven_kategori' => 'N',
            ],
            [
                'kode_obat' => '92000517',
                'nama_obat' => 'Ascorbic Acid (Vitamin C) Tablet 50 mg',
                'nama_generik' => 'Ascorbic Acid',
                'kategori' => 'Vitamin & Suplemen',
                'satuan' => 'Tablet',
                'kekuatan' => '50 mg',
                'bentuk_sediaan' => 'tablet',
                'ven_kategori' => 'N',
            ],
            [
                'kode_obat' => '92000129',
                'nama_obat' => 'Ascorbic Acid (Vitamin C) Tablet 250 mg',
                'nama_generik' => 'Ascorbic Acid',
                'kategori' => 'Vitamin & Suplemen',
                'satuan' => 'Tablet',
                'kekuatan' => '250 mg',
                'bentuk_sediaan' => 'tablet',
                'ven_kategori' => 'N',
            ],
            [
                'kode_obat' => '92000472',
                'nama_obat' => 'Asiklovir Tablet 200 mg',
                'nama_generik' => 'Asiklovir',
                'kategori' => 'Antiinfeksi',
                'satuan' => 'Tablet',
                'kekuatan' => '200 mg',
                'bentuk_sediaan' => 'tablet',
                'ven_kategori' => 'E',
            ],
            [
                'kode_obat' => '92000770',
                'nama_obat' => 'Asiklovir Tablet 400 mg',
                'nama_generik' => 'Asiklovir',
                'kategori' => 'Antiinfeksi',
                'satuan' => 'Tablet',
                'kekuatan' => '400 mg',
                'bentuk_sediaan' => 'tablet',
                'ven_kategori' => 'E',
            ],
            [
                'kode_obat' => '92001095',
                'nama_obat' => 'Aciclovir 50 mg/g Krim',
                'nama_generik' => 'Asiklovir',
                'kategori' => 'Kulit & Topikal',
                'satuan' => 'Tube',
                'kekuatan' => '50 mg/g',
                'bentuk_sediaan' => 'salep',
                'ven_kategori' => 'N',
            ],
            [
                'kode_obat' => '92000435',
                'nama_obat' => 'Diazepam Tablet 5 mg',
                'nama_generik' => 'Diazepam',
                'kategori' => 'Psikotropika & Saraf',
                'satuan' => 'Tablet',
                'kekuatan' => '5 mg',
                'bentuk_sediaan' => 'tablet',
                'ven_kategori' => 'V',
            ],
            [
                'kode_obat' => '92000914',
                'nama_obat' => 'Furosemid Tablet 40 mg',
                'nama_generik' => 'Furosemid',
                'kategori' => 'Kardiovaskular',
                'satuan' => 'Tablet',
                'kekuatan' => '40 mg',
                'bentuk_sediaan' => 'tablet',
                'ven_kategori' => 'E',
            ],
            [
                'kode_obat' => '92000634',
                'nama_obat' => 'Epinephrine 1 mg/mL Injeksi',
                'nama_generik' => 'Epinephrine',
                'kategori' => 'Anestesi & Emergensi',
                'satuan' => 'Ampul',
                'kekuatan' => '1 mg/mL',
                'bentuk_sediaan' => 'injeksi',
                'ven_kategori' => 'V',
            ],
            [
                'kode_obat' => '92000465',
                'nama_obat' => 'Fitomenadion Tablet 10 mg',
                'nama_generik' => 'Fitomenadion',
                'kategori' => 'Darah',
                'satuan' => 'Tablet',
                'kekuatan' => '10 mg',
                'bentuk_sediaan' => 'tablet',
                'ven_kategori' => 'N',
            ],
            [
                'kode_obat' => '92002848',
                'nama_obat' => 'Garam Oralit Serbuk',
                'nama_generik' => 'Oralit',
                'kategori' => 'Obat Bebas',
                'satuan' => 'Sachet',
                'kekuatan' => null,
                'bentuk_sediaan' => 'sirup',
                'ven_kategori' => 'N',
            ],
            [
                'kode_obat' => '92000163',
                'nama_obat' => 'Glimepirid Tablet 2 mg',
                'nama_generik' => 'Glimepirid',
                'kategori' => 'Endokrin & Metabolik',
                'satuan' => 'Tablet',
                'kekuatan' => '2 mg',
                'bentuk_sediaan' => 'tablet',
                'ven_kategori' => 'E',
            ],
            [
                'kode_obat' => '92000445',
                'nama_obat' => 'Haloperidol Tablet 5 mg',
                'nama_generik' => 'Haloperidol',
                'kategori' => 'Psikotropika & Saraf',
                'satuan' => 'Tablet',
                'kekuatan' => '5 mg',
                'bentuk_sediaan' => 'tablet',
                'ven_kategori' => 'E',
            ],
            [
                'kode_obat' => '92000185',
                'nama_obat' => 'Ibuprofen Suspensi 100 mg/5 mL',
                'nama_generik' => 'Ibuprofen',
                'kategori' => 'Analgesik & Antiinflamasi',
                'satuan' => 'Botol',
                'kekuatan' => '100 mg/5 mL',
                'bentuk_sediaan' => 'sirup',
                'ven_kategori' => 'E',
            ],
            [
                'kode_obat' => '92001081',
                'nama_obat' => 'Ibuprofen 400 mg Tablet Salut Selaput',
                'nama_generik' => 'Ibuprofen',
                'kategori' => 'Analgesik & Antiinflamasi',
                'satuan' => 'Tablet',
                'kekuatan' => '400 mg',
                'bentuk_sediaan' => 'tablet',
                'ven_kategori' => 'E',
            ],
            [
                'kode_obat' => '92001124',
                'nama_obat' => 'Kalsium Laktat 500 mg Tablet',
                'nama_generik' => 'Kalsium Laktat',
                'kategori' => 'Vitamin & Suplemen',
                'satuan' => 'Tablet',
                'kekuatan' => '500 mg',
                'bentuk_sediaan' => 'tablet',
                'ven_kategori' => 'N',
            ],
            [
                'kode_obat' => '92000344',
                'nama_obat' => 'Captopril 25 mg Tablet',
                'nama_generik' => 'Captopril',
                'kategori' => 'Kardiovaskular',
                'satuan' => 'Tablet',
                'kekuatan' => '25 mg',
                'bentuk_sediaan' => 'tablet',
                'ven_kategori' => 'E',
            ],
            [
                'kode_obat' => '92000572',
                'nama_obat' => 'Betametason Krim 0,1%',
                'nama_generik' => 'Betametason',
                'kategori' => 'Antialergi & Imunologi',
                'satuan' => 'Tube',
                'kekuatan' => '0,1%',
                'bentuk_sediaan' => 'salep',
                'ven_kategori' => 'E',
            ],
            [
                'kode_obat' => '92000706',
                'nama_obat' => 'Prednison Tablet 5 mg',
                'nama_generik' => 'Prednison',
                'kategori' => 'Antialergi & Imunologi',
                'satuan' => 'Tablet',
                'kekuatan' => '5 mg',
                'bentuk_sediaan' => 'tablet',
                'ven_kategori' => 'E',
            ],
            [
                'kode_obat' => '92001386',
                'nama_obat' => 'Sulfamethoxazole 400 mg / Trimethoprim 80 mg Tablet',
                'nama_generik' => 'Sulfamethoxazole; Trimethoprim',
                'kategori' => 'Antiinfeksi',
                'satuan' => 'Tablet',
                'kekuatan' => '400 mg; 80 mg',
                'bentuk_sediaan' => 'tablet',
                'ven_kategori' => 'E',
            ],
            [
                'kode_obat' => '92000986',
                'nama_obat' => 'Lidocain HCl Monohydrate 2% Injeksi',
                'nama_generik' => 'Lidocain Hydrochloride',
                'kategori' => 'Anestesi & Emergensi',
                'satuan' => 'Ampul',
                'kekuatan' => '2%',
                'bentuk_sediaan' => 'injeksi',
                'ven_kategori' => 'V',
            ],
            [
                'kode_obat' => '92000209',
                'nama_obat' => 'Metformin HCl 500 mg Tablet',
                'nama_generik' => 'Metformin Hydrochloride',
                'kategori' => 'Endokrin & Metabolik',
                'satuan' => 'Tablet',
                'kekuatan' => '500 mg',
                'bentuk_sediaan' => 'tablet',
                'ven_kategori' => 'E',
            ],
            [
                'kode_obat' => '92000535',
                'nama_obat' => 'Diclofenac Sodium 50 mg Tablet Salut Enterik',
                'nama_generik' => 'Diclofenac Sodium',
                'kategori' => 'Analgesik & Antiinflamasi',
                'satuan' => 'Tablet',
                'kekuatan' => '50 mg',
                'bentuk_sediaan' => 'tablet',
                'ven_kategori' => 'E',
            ],
            [
                'kode_obat' => '92000715',
                'nama_obat' => 'OAT FDC Kat 1 (Rifampicin 150 mg; Isoniazid 75 mg; Pyrazinamide 400 mg; Ethambutol 275 mg)',
                'nama_generik' => 'Rifampicin; Isoniazid; Pyrazinamide; Ethambutol',
                'kategori' => 'Antiinfeksi',
                'satuan' => 'Tablet',
                'kekuatan' => '150 mg; 75 mg; 400 mg; 275 mg',
                'bentuk_sediaan' => 'tablet',
                'ven_kategori' => 'V',
            ],
            [
                'kode_obat' => '92000756',
                'nama_obat' => 'Oksitosin Injeksi 10 IU/mL',
                'nama_generik' => 'Oksitosin',
                'kategori' => 'Anestesi & Emergensi',
                'satuan' => 'Ampul',
                'kekuatan' => '10 IU/mL',
                'bentuk_sediaan' => 'injeksi',
                'ven_kategori' => 'V',
            ],
            [
                'kode_obat' => '92001960',
                'nama_obat' => 'Omeprazole Kapsul 20 mg',
                'nama_generik' => 'Omeprazole',
                'kategori' => 'Pencernaan',
                'satuan' => 'Kapsul',
                'kekuatan' => '20 mg',
                'bentuk_sediaan' => 'kapsul',
                'ven_kategori' => 'E',
            ],
            [
                'kode_obat' => '92001267',
                'nama_obat' => 'Parasetamol Tablet 500 mg',
                'nama_generik' => 'Parasetamol',
                'kategori' => 'Analgesik & Antiinflamasi',
                'satuan' => 'Tablet',
                'kekuatan' => '500 mg',
                'bentuk_sediaan' => 'tablet',
                'ven_kategori' => 'E',
            ],
            [
                'kode_obat' => '92001885',
                'nama_obat' => 'Pyridoxine HCl 25 mg Kaplet',
                'nama_generik' => 'Pyridoxine Hydrochloride',
                'kategori' => 'Vitamin & Suplemen',
                'satuan' => 'Tablet',
                'kekuatan' => '25 mg',
                'bentuk_sediaan' => 'tablet',
                'ven_kategori' => 'N',
            ],
            [
                'kode_obat' => '92000347',
                'nama_obat' => 'Primakuin Tablet 25 mg',
                'nama_generik' => 'Primakuin',
                'kategori' => 'Antimalaria',
                'satuan' => 'Tablet',
                'kekuatan' => '25 mg',
                'bentuk_sediaan' => 'tablet',
                'ven_kategori' => 'V',
            ],
            [
                'kode_obat' => '92003720',
                'nama_obat' => 'Ranitidine HCl 150 mg Tablet',
                'nama_generik' => 'Ranitidine Hydrochloride',
                'kategori' => 'Pencernaan',
                'satuan' => 'Tablet',
                'kekuatan' => '150 mg',
                'bentuk_sediaan' => 'tablet',
                'ven_kategori' => 'E',
            ],
            [
                'kode_obat' => '92000809',
                'nama_obat' => 'Retinol Palmitate 200.000 IU Kapsul Lunak',
                'nama_generik' => 'Retinol Palmitate',
                'kategori' => 'Vitamin & Suplemen',
                'satuan' => 'Kapsul',
                'kekuatan' => '200.000 IU',
                'bentuk_sediaan' => 'kapsul',
                'ven_kategori' => 'N',
            ],
            [
                'kode_obat' => '92000860',
                'nama_obat' => 'Salbutamol Tablet 2 mg',
                'nama_generik' => 'Salbutamol',
                'kategori' => 'Pernapasan',
                'satuan' => 'Tablet',
                'kekuatan' => '2 mg',
                'bentuk_sediaan' => 'tablet',
                'ven_kategori' => 'E',
            ],
            [
                'kode_obat' => '92000731',
                'nama_obat' => 'Gentamisin Salep Mata 0,3%',
                'nama_generik' => 'Gentamisin',
                'kategori' => 'Kulit & Topikal',
                'satuan' => 'Tube',
                'kekuatan' => '0,3%',
                'bentuk_sediaan' => 'salep',
                'ven_kategori' => 'N',
            ],
            [
                'kode_obat' => '92000366',
                'nama_obat' => 'Simvastatin Tablet 10 mg',
                'nama_generik' => 'Simvastatin',
                'kategori' => 'Kardiovaskular',
                'satuan' => 'Tablet',
                'kekuatan' => '10 mg',
                'bentuk_sediaan' => 'tablet',
                'ven_kategori' => 'E',
            ],
            [
                'kode_obat' => '92000564',
                'nama_obat' => 'Tenofovir Disoproksil Fumarat 300 mg / Lamivudin 300 mg / Efavirenz 600 mg Tablet',
                'nama_generik' => 'Tenofovir; Lamivudin; Efavirenz',
                'kategori' => 'Antiretroviral',
                'satuan' => 'Tablet',
                'kekuatan' => '300 mg; 300 mg; 600 mg',
                'bentuk_sediaan' => 'tablet',
                'ven_kategori' => 'V',
            ],
            [
                'kode_obat' => '92000201',
                'nama_obat' => 'Zinc Sulfate Monohydrate 20 mg Tablet Dispersible',
                'nama_generik' => 'Zinc Sulfate',
                'kategori' => 'Vitamin & Suplemen',
                'satuan' => 'Tablet',
                'kekuatan' => '20 mg',
                'bentuk_sediaan' => 'tablet',
                'ven_kategori' => 'N',
            ],
        ];

        foreach ($obatList as $obat) {
            $obat['harga_satuan'] = $this->randomHarga($obat['satuan']);

            Obat::firstOrCreate(
                ['kode_obat' => $obat['kode_obat']],
                $obat,
            );
        }

        Obat::whereNull('harga_satuan')
            ->orWhere('harga_satuan', 0)
            ->eachById(function (Obat $obat) {
                $obat->update([
                    'harga_satuan' => $this->randomHarga($obat->satuan),
                ]);
            });

        Obat::whereNull('ven_kategori')
            ->eachById(function (Obat $obat) {
                $obat->update([
                    'ven_kategori' => $this->getVenKategori($obat->kode_obat),
                ]);
            });
    }

    private function getVenKategori(string $kodeObat): string
    {
        return self::VEN_MAP[$kodeObat] ?? 'E';
    }

    private function randomHarga(string $satuan): float
    {
        [$min, $max] = self::HARGA_RANGES[$satuan] ?? [500, 50000];

        return fake()->randomFloat(2, $min, $max);
    }
}
